featured: false

title:
  fa: "Link Sawing"
  en: "Link Sawing"

description:
  fa: "یک افزونه وردپرس برای مدیریت و کنترل لینک‌ها، slugها و permalinkها با تمرکز بر انعطاف‌پذیری و سازگاری با WooCommerce."
  en: "A flexible WordPress plugin for managing and controlling links, slugs, and permalinks, with WooCommerce compatibility."

banner: null

preview: null

skills:
  - name: "WordPress"
    icon:
      light: "skill-icons:wordpress"
      dark: "skill-icons:wordpress"

  - name: "PHP"
    icon:
      light: "skill-icons:php-light"
      dark: "skill-icons:php-dark"

  - name: "WooCommerce"
    icon:
      light: "logos:woocommerce-icon"
      dark: "logos:woocommerce-icon"

  - name: "GitHub"
    icon:
      light: "skill-icons:github-light"
      dark: "skill-icons:github-dark"
